export const savedJobsData =[
    {company:"Infosys",
title: "Data Analyst",
exp : 2,
location: "Seattle, WA",
type: "Contract",
workSetting: "Offsite",
salary: "$3,000/month",
date: "Jan 12,2025",
h1Type: "H-1B Jobs",
applyLink: ""
},
{
company:"Infosis",
title: "Data Analyst",
exp : 2,
location: "Seattle, LA",
type: "Contract",
workSetting: "Onsite",
salary: "$3,000/month",
date: "Jan 12,2025",
h1Type: "H-1B Jobs",
applyLink: ""
},
{
company:"Infosys",
title: "Data Analyst",
exp : 2,
location: "Seattle, WA",
type: "Full-Time",
workSetting: "Onsite",
salary: "$3,000/month",
date: "Jan 12,2025",
h1Type: "H-1B Jobs",
applyLink: ""
},
{
company:"Infosys",
title: "Data Analyst",
exp : 3,
location: "Seattle, LA",
type: "Full-Time",
workSetting: "Onsite",
salary: "$6,000/month",
date: "Jan 12,2025",
h1Type: "H-1B Jobs",
applyLink: ""
},
{
company:"Infosys",
title: "Data Analyst",
exp : 2,
location: "Seattle, WA",
type: "Full-Time",
workSetting: "Onsite",
salary: "$3,000/month",
date: "Jan 12,2025",
h1Type: "H-1B Jobs",
applyLink: ""
},
]
