// import {JobData}  from "../jobsAfterSignIn/jobData";

// const personsInterestedCategory = "Data Analyst";
// export const jobDataFreePlan = jobData.filter((stat,i) => (
//     stat.title === personsInterestedCategory
// ))

import React, { useEffect } from 'react';
import Papa from 'papaparse';




export function JobDataFreePlan(props){
    let jobListings=[];
    let jobListingsData=[];

    useEffect(()=>{
        Papa.parse("./jobDataCsv/jobListing.csv", {
            download: true,
            header: true, 
            // worker:true, 
            skipEmptyLines :true,
            complete: function(results) {
                console.log(results);
                jobListings = results.data.map(job => ({
                    company: job['Company Name '],
                    title: job['Job Title '],
                    exp : job['Experience (in years)'],
                    location: job['Location '],
                    type: job['Job Type '],
                    workSetting: job['Work Setting'],
                    salary: job['Salary Range'],
                    date: job['Posted Date'],
                    h1Type: "H-1B Jobs",
                    applyLink: job['Job URL'],
                    responsibility: job['Responsibilities and Requirements'],
                    logo:job['Company Logo'],
                    expText : job['Experience Level'],
                    smallDesc: job['Job Description'],
                    fullDesc : job['Full Job Description'],
                    skills: job['Skills']
                }));
                jobListingsData = jobListings;
                console.log(jobListingsData); 
                props.setJobDataFreePlan(jobListingsData);
            }
        });
    },[])
    
    

    return (
        <div></div>
    ); 
}









// export const jobData = [
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Contract",
//         workSetting: "Offsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosis",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, LA",
//         type: "Contract",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 3,
//         location: "Seattle, LA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$6,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "H-1B Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Full-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: ""
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Part-Time",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Internship",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Internship",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
//     {
//         company:"Infosys",
//         title: "Data Analyst",
//         exp : 2,
//         location: "Seattle, WA",
//         type: "Contract",
//         workSetting: "Onsite",
//         salary: "$3,000/month",
//         date: "Jan 12,2025",
//         h1Type: "Cap-Exempt Jobs",
//         applyLink: "",
//     },
// ]
